### ISSUE TITLE
Compatibility with Arduino IDE 2.3.2

### ISSUE THREAD

**Issue by Zim-Zalabim** [dankeboy36/esp-exception-decoder#26]
Does this work with 2.3.2? I'm getting this error when I open the software.
![image](https://github.com/user-attachments/assets/20bbf698-dd9d-498e-977c-dcf0932b6730)
.

**Comment by dankeboy36** [comment]
Please see https://github.com/dankeboy36/esp-exception-decoder/issues/17#issuecomment-1974804485 and let me know if you can solve the problem.

The installation instructions are here: https://github.com/dankeboy36/esp-exception-decoder?tab=readme-ov-file#installation

If you get stuck, you can ask for help on the official Arduino forum, I am sure people are happy to help you: https://forum.arduino.cc/c/software/ide-2-x/93
