### ISSUE TITLE
Version for IDE 2.3.4?

### ISSUE THREAD

**Issue by philmay57** [dankeboy36/esp-exception-decoder#35]
Just installed 2.3.4 and decoder kept asking for the application to be rebuilt.  Backed out to a copy of IDE 2.3.2 I had downloaded, rebuilt app and the decoder then decoded the stack trace for me, but a pain to have to reinstall the old IDE for every non-obvious crash.

**Comment by dankeboy36** [comment]
Thanks for using the decoder extension.

I updated Arduino IDE to 2.3.4, and I could not reproduce anything like you have reported.

<img width="680" alt="Screen Shot 2024-12-03 at 19 43 09" src="https://github.com/user-attachments/assets/6b644044-f248-4731-9415-653cbcc15ec5">


> Just installed 2.3.4 and decoder kept asking for the application to be rebuilt.

Can you share a screencast or a screenshot, at least?

> I had downloaded, rebuilt app and the decoder

What did you do?

**Comment by philmay57** [comment]
Hi, thanks for the prompt response.  I just reinstalled 2.3.4 and of course now it all works fine.  Apologies for wasting your time, and thanks for supporting this excellent plugin.
Regards
Phil
