### ISSUE TITLE
Fails to use esp-exception-decoder with Arduino IDE 2.1.1

### ISSUE THREAD

**Issue by ceerqingtingml** [dankeboy36/esp-exception-decoder#9]
**Description:**
I can find the esp exception decoder in Arduino IDE, but cannot use it, any suggestion would be appreciated.
![image](https://github.com/dankeboy36/esp-exception-decoder/assets/19239201/6a0a2fef-b518-4a43-b4fb-acab869aa8db)
![image](https://github.com/dankeboy36/esp-exception-decoder/assets/19239201/3a153056-87b8-45e3-a94e-3db579354761)
![image](https://github.com/dankeboy36/esp-exception-decoder/assets/19239201/3d7cefc7-9987-497c-8132-1239b3f04715)

Related:
 - https://github.com/dankeboy36/esp-exception-decoder/issues/7
 - https://github.com/dankeboy36/esp-exception-decoder/issues/8

**Comment by per1234** [comment]
Hi @ceerqingtingml. The support for the extension was added after the time of the Arduino IDE 2.1.1 release. It is expected that you will get this error when using the extension with an incompatible version of Arduino IDE.

Please try again with the latest nightly build of Arduino IDE. The download links for the nightly build are listed here:

https://www.arduino.cc/en/software#nightly-builds

---

Alternatively, if you prefer not to use the nightly build of Arduino IDE, you can just wait until the next IDE release comes out (e.g., Arduino IDE 2.1.2). The support for the extension will be included in that upcoming release.
